# Generated by Django 5.1.1 on 2025-11-29 07:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_alert_frequency', models.CharField(choices=[('realtime', '即時通知'), ('hourly', '每小時'), ('daily', '每日'), ('weekly', '每週'), ('disabled', '停用通知')], default='daily', help_text='設定接收庫存不足通知的頻率', max_length=20, verbose_name='庫存警告頻率')),
                ('email_notification', models.BooleanField(default=True, help_text='是否接收 Email 通知', verbose_name='Email 通知')),
                ('browser_notification', models.BooleanField(default=True, help_text='是否接收瀏覽器即時通知', verbose_name='瀏覽器通知')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preference', to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
            ],
            options={
                'verbose_name': '使用者偏好設定',
                'verbose_name_plural': '使用者偏好設定',
            },
        ),
    ]
