# Generated by Django 5.1.1 on 2025-11-29 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userpreference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreference',
            name='stock_alert_frequency',
            field=models.CharField(choices=[('every_15_sec', '每 15 秒（測試用）'), ('every_minute', '每分鐘'), ('hourly', '每小時'), ('daily', '每日'), ('weekly', '每週'), ('disabled', '停用通知')], default='daily', help_text='設定接收庫存不足通知的頻率', max_length=20, verbose_name='庫存警告頻率'),
        ),
    ]
